title: Wayra Liao
name: Wayra Liao
description: Portfolio & Notes
url: "https://wayraliao.github.io"
baseurl: ""

# Pin to a real tag (avoid @latest ambiguity)
remote_theme: "mmistakes/minimal-mistakes@4.26.0"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-include-cache

minimal_mistakes_skin: "default"

author:
  name: "Wayra Liao"
  bio: "Data science, XAI, research."

# Output pages from _pages/
collections:
  pages:
    output: true

navigation:
  header: main
