title: Wayra Liao
name: Wayra Liao
description: Personal Website Test
url: "https://wayraliao.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes@latest"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-include-cache

minimal_mistakes_skin: "default"

author:
  name: "Wayra Liao"
  bio: "Data science, XAI, and research."
