title: Wayra Liao
name: Wayra Liao
description: Portfolio & Notes
url: "https://wayraliao.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-include-cache

minimal_mistakes_skin: "default"

author:
  name: "Wayra Liao"
  bio: "Data science, XAI, research."
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/wayraliao"

# 宣告 _pages 會輸出，並套預設版型
collections:
  pages:
    output: true

defaults:
  - scope: { path: "", type: "pages" }
    values:
      layout: single
      author_profile: true
  - scope: { path: "", type: "posts" }
    values:
      layout: single
      author_profile: true

# 啟用導覽列，實際項目放在 _data/navigation.yml
navigation:
  header: nav_main
