title: Wayra Liao
name: Wayra Liao
description: Personal Website Test
url: "https://wayraliao.github.io"
baseurl: ""

# 正確：不用 @latest，直接指定倉庫即可
remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-include-cache

minimal_mistakes_skin: "default"

author:
  name: "Wayra Liao"
  bio: "Data science, XAI, and research."
