title: Wayra Liao
name: Wayra Liao
description: Portfolio & Notes
url: "https://wayraliao.github.io"
baseurl: ""

# Pin to a real tag (avoid @latest ambiguity)
remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-include-cache

minimal_mistakes_skin: "default"

author:
  name: "Wayra Liao"
  bio: "Data science, XAI, research."

# Output pages from _pages/
collections:
  pages:
    output: true
  projects:
    output: true
    permalink: /projects/:title/

# 讓 projects 集合的每篇自動帶上 show-pager
defaults:
  - scope: { path: "", type: "pages" }
    values:
      layout: single
      author_profile: true
  - scope: { path: "", type: "posts" }
    values:
      layout: single
      author_profile: true
  - scope: { path: "", type: "projects" }
    values:
      layout: single         # 可以保留 single 版型
      author_profile: true
      classes: show-pager    # ★ 關鍵：只有 projects 內頁帶這個 class

navigation:
  header: main
